CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id    BIGINT
    constraint items_owner_id
    references users
);

CREATE TABLE IF NOT EXISTS user_items (
    item_id BIGINT constraint user_items_items_id_fk
        references items,
    user_id BIGINT constraint user_items_users_id_fk
        references users
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    item_id BIGINT CONSTRAINT bookings_items_id_fk
        references items,
    booker_id BIGINT CONSTRAINT bookings_users_id_fk
        references users,
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    requestor_id BIGINT
);

create table if not exists comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    item_id   BIGINT
        constraint comments_items_id_fk
        references items,
    author_id bigint
        constraint comments_users_id_fk
        references users
);